# Faça um programa que na tela uma contagem regressiva para o estouro de fogos de artifício, indo de 10 até 0 com
# um segundo de pausa entre eles
from time import sleep
print('10')
sleep(1)
print('9')
sleep(1)
print('8')
sleep(1)
print('7')
sleep(1)
print('6')
sleep(1)
print('5')
sleep(1)
print('4')
sleep(1)
print('3')
sleep(1)
print('2')
sleep(1)
print('1')
sleep(1)
print('0')
sleep(1)
print('Fogooo!!!')